apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.name }}
        args:
        - '--log.level=debug'
        - '--web.listen-address=:{{ .Values.port }}'
        - '--collector.arp'
        - '--collector.bcache'
        - '--collector.conntrack'
        - '--collector.cpu'
        - '--collector.diskstats'
        - '--collector.edac'
        - '--collector.entropy'
        - '--collector.filefd'
        - '--collector.filesystem'
        - '--collector.hwmon'
        - '--collector.infiniband'
        - '--collector.ipvs'
        - '--collector.loadavg'
        - '--collector.mdadm'
        - '--collector.meminfo'
        - '--collector.netdev'
        - '--collector.netstat'
        - '--collector.sockstat'
        - '--collector.stat'
        - '--collector.systemd'
        - '--no-collector.textfile'   # we don't use textfile collector.
        - '--collector.time'
        - '--collector.timex'
        - '--collector.uname'
        - '--collector.vmstat'
        - '--no-collector.wifi'       # we don't use wifi.
        - '--collector.xfs'
        - '--no-collector.zfs'        # we don't use zfs.
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: systemd-volume
      volumes:
      - name: systemd-volume
        hostPath:
          path: /var/run/dbus/
      serviceAccountName: {{ .Values.name }}
      hostNetwork: true
      hostPID: true
