apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
        giantswarm.io/service-type: "managed"
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      securityContext:
        runAsUser: 0
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.name }}
        ports:
        - name: metrics
          containerPort: {{ .Values.port }}
        args:
        - '--log.level=info'
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--web.listen-address=:{{ .Values.port }}'

        - '--collector.arp'
        - '--collector.bcache'
        - '--collector.conntrack'
        - '--collector.cpu'
        - '--collector.edac'
        - '--collector.entropy'
        - '--collector.filefd'
        - '--collector.filesystem'
        - '--collector.hwmon'
        - '--collector.ipvs'
        - '--collector.loadavg'
        - '--collector.mdadm'
        - '--collector.meminfo'
        - '--collector.netdev'
        - '--collector.netstat'
        - '--collector.sockstat'
        - '--collector.stat'
        - '--collector.systemd'
        - '--collector.time'
        - '--collector.timex'
        - '--collector.uname'
        - '--collector.vmstat'
        - '--collector.xfs'

        - '--no-collector.diskstats'
        - '--no-collector.infiniband'
        - '--no-collector.textfile'
        - '--no-collector.wifi'
        - '--no-collector.zfs'
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: root
          mountPath: /rootfs
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: var-lib-docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - mountPath: /var/run/dbus/
          name: var-run-dbus
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: root
        hostPath:
          path: /
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus/
      serviceAccountName: {{ .Values.name }}
      hostNetwork: true
      hostPID: true
