apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: kube-system
roleRef:
  kind: Role
  name: node-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
rules:
- apiGroups:     ['extensions']
  resources:     ['podsecuritypolicies']
  resourceNames: ['node-exporter-psp']
  verbs:         ['use']
