apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  ports:
  - port: {{ .Values.port }}
    name: metrics
    targetPort: metrics

  selector:
    app: {{ .Values.name }}
