apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - ""
  resources:
  - clusterroles
  - clusterrolebindings
  - deployments
  - services
  - serviceaccounts
  verbs:
  - "get"
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
