apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
