apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - image: quay.io/giantswarm/node-exporter:v0.15.1
        name: node-exporter
        args:
          - '--log.level=debug'
          - '--web.listen-address=:10300'
          - '--collector.arp'
          - '--collector.bcache'
          - '--collector.conntrack'
          - '--collector.cpu'
          - '--collector.diskstats'
          - '--collector.edac'
          - '--collector.entropy'
          - '--collector.filefd'
          - '--collector.filesystem'
          - '--collector.hwmon'
          - '--collector.infiniband'
          - '--collector.ipvs'
          - '--collector.loadavg'
          - '--collector.mdadm'
          - '--collector.meminfo'
          - '--collector.netdev'
          - '--collector.netstat'
          - '--collector.sockstat'
          - '--collector.stat'
          - '--collector.systemd'
          - '--no-collector.textfile'   # we don't use textfile collector.
          - '--collector.time'
          - '--collector.timex'
          - '--collector.uname'
          - '--collector.vmstat'
          - '--no-collector.wifi'       # we don't use wifi.
          - '--collector.xfs'
          - '--no-collector.zfs'        # we don't use zfs.
        livenessProbe:
          httpGet:
            path: /
            port: 10300
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 10300
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 55m
            memory: 75Mi
          limits:
            cpu: 55m
            memory: 75Mi
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: systemd-volume
      volumes:
      - name: systemd-volume
        hostPath:
          path: /var/run/dbus/
      serviceAccountName: node-exporter
      hostNetwork: true
      hostPID: true
